SELECT_EMPLOYEE=
SELECT
    EMPLOYEE.EMPLOYEE_ID,
    EMPLOYEE.FULL_NAME,
    EMPLOYEE.BASIC_SALARY,
    EMPLOYEE.GRADE_CODE,
    GRADE.BONUS_MAGNIFICATION,
    GRADE.FIXED_BONUS
FROM
    EMPLOYEE
INNER JOIN GRADE ON EMPLOYEE.GRADE_CODE = GRADE.GRADE_CODE